[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
fastrand = "2.3.0"
macroquad = { git = "https://github.com/LukyDrum/macroquad.git" }
num-traits = "0.2.19"
rayon = "1.10.0"
serde = "1.0.218"
serde_derive = "1.0.218"
serde_json = "1.0.140"
