[package]
name = "game_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
macroquad = { git = "https://github.com/LukyDrum/macroquad.git" }
quote = "1.0.40"
syn = "2.0.100"
